-- Core relational tables mirroring backend/prisma/schema.prisma
-- Models: Farmer -> farmers, Listing -> listings, Order -> orders, Attestation -> attestations
--
-- NOTE: These tables are normally written by the Express backend via Prisma
-- (which connects as the postgres role and bypasses RLS). RLS is enabled below
-- as a secure default so the anon/publishable key has NO access. If you later
-- read/write these directly from the browser, add explicit policies.

-- Auto-update `updated_at` on row updates.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ── farmers ────────────────────────────────────────────────────────
create table if not exists public.farmers (
  id             text        primary key,
  full_name      text        not null,
  farm_name      text        not null,
  region         text        not null,
  total_yield_kg integer     not null default 0,
  id_doc_path    text,
  verified       boolean     not null default false,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

drop trigger if exists farmers_set_updated_at on public.farmers;
create trigger farmers_set_updated_at
  before update on public.farmers
  for each row execute function public.set_updated_at();

-- ── listings ───────────────────────────────────────────────────────
create table if not exists public.listings (
  id             integer generated by default as identity primary key,
  nft_id         integer          not null unique,
  crop_type      text,
  quantity_kg    integer,
  price_usdc     double precision,
  farmer_id      text             not null references public.farmers(id) on delete cascade,
  parcel_name    text,
  region         text,
  buyable        boolean          not null default false,
  ndvi_bps       integer,
  min_ndvi_bps   integer,
  area_ha        double precision,
  total_yield_kg integer,
  status         text             not null default 'minted',
  tx_hash        text,
  created_at     timestamptz      not null default now(),
  updated_at     timestamptz      not null default now()
);

create index if not exists listings_farmer_id_idx on public.listings(farmer_id);

drop trigger if exists listings_set_updated_at on public.listings;
create trigger listings_set_updated_at
  before update on public.listings
  for each row execute function public.set_updated_at();

-- ── orders ─────────────────────────────────────────────────────────
create table if not exists public.orders (
  id            text             primary key default gen_random_uuid()::text,
  listing_id    integer          not null references public.listings(id) on delete cascade,
  buyer_address text             not null,
  amount_usdc   double precision not null,
  tx_hash       text,
  status        text             not null default 'escrow',
  created_at    timestamptz      not null default now(),
  updated_at    timestamptz      not null default now()
);

create index if not exists orders_listing_id_idx on public.orders(listing_id);

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
  before update on public.orders
  for each row execute function public.set_updated_at();

-- ── attestations ───────────────────────────────────────────────────
create table if not exists public.attestations (
  id           integer generated by default as identity primary key,
  nft_id       integer     not null,
  observed_at  timestamptz not null,
  ndvi_bps     integer     not null,
  min_ndvi_bps integer     not null,
  buyable      boolean     not null,
  bbox_hash    text        not null,
  report_hash  text        not null,
  source       text        not null,
  created_at   timestamptz not null default now(),
  unique (nft_id, observed_at)
);

-- ── Row Level Security ──────────────────────────────────────────────
alter table public.farmers      enable row level security;
alter table public.listings     enable row level security;
alter table public.orders       enable row level security;
alter table public.attestations enable row level security;

-- Allow read/write for anon (used by server-side Next.js API routes)
drop policy if exists "farmers_all" on public.farmers;
create policy "farmers_all" on public.farmers for all to anon using (true) with check (true);

drop policy if exists "listings_all" on public.listings;
create policy "listings_all" on public.listings for all to anon using (true) with check (true);

drop policy if exists "orders_all" on public.orders;
create policy "orders_all" on public.orders for all to anon using (true) with check (true);

drop policy if exists "attestations_all" on public.attestations;
create policy "attestations_all" on public.attestations for all to anon using (true) with check (true);
